from setuptools import setup, find_packages

setup(
    name="tech-stocks-analyzer",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "streamlit>=1.28.0",
        "pandas>=2.2.0,<3.0.0",
        "yfinance>=0.2.18",
        "requests>=2.31.0",
        "beautifulsoup4>=4.12.0",
        "lxml>=4.9.0",
        "plotly>=5.15.0",
        "numpy>=1.24.0,<2.0.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "google-generativeai>=0.3.0",
        "python-dotenv>=1.0.0",
    ],
    python_requires=">=3.8,<3.13",
    author="Your Name",
    author_email="your.email@example.com",
    description="A comprehensive tech stocks investment analyzer with AI-powered recommendations",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/tech-stocks-analyzer",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
)
